name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # pnpm を確実にインストール（ここが無いと今回のエラーになる）
      - name: Install pnpm
        run: |
          npm -g i pnpm@10.15.0
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Lint (non-blocking)
        run: pnpm run lint || true

      - name: Type check (non-blocking)
        run: pnpm run type-check || true

      - name: Build
        run: pnpm run build
